gcc 7.1 fallthru error workaround
Newer gcc requires switch fallthrus are explicitly annotated with a comment.  Fedora 26 for example now has GCC7.1 and compilation fails.

Although these seem a bit suspicious to me, this patch keeps the current program structure
and provides the necessary annotation comments.

Problem 1:

[ 18%] Building CXX object src/CMakeFiles/clDNN_shlib.dir/fully_connected.cpp.o
/projects/cldnn/src/fully_connected.cpp: In function ‘bool cldnn::{anonymous}::is_batch_after_spatial(std::string)’:
/projects/cldnn/src/fully_connected.cpp:42:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (spatial_found)
             ^~
/projects/cldnn/src/fully_connected.cpp:44:9: note: here
         case 'x':
         ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/clDNN_shlib.dir/build.make:509: src/CMakeFiles/clDNN_shlib.dir/fully_connected.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: src/CMakeFiles/clDNN_shlib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Problem 2:

[ 45%] Building CXX object src/CMakeFiles/clDNN_shlib.dir/gpu/softmax_gpu.cpp.o
/projects/cldnn/src/gpu/softmax_gpu.cpp: In static member function ‘static neural::softmax_gpu::kernel_data neural::softmax_gpu::set_kernel_data(const softmax_node&)’:
/projects/cldnn/src/gpu/softmax_gpu.cpp:90:58: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case softmax::normalize_bfyx:   kd.data_set_size *= input_size.batch[0];
/projects/cldnn/src/gpu/softmax_gpu.cpp:91:9: note: here
         case softmax::normalize_fyx:    kd.data_set_size *= input_size.feature[0];
         ^~~~
/projects/cldnn/src/gpu/softmax_gpu.cpp:91:58: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case softmax::normalize_fyx:    kd.data_set_size *= input_size.feature[0];
/projects/cldnn/src/gpu/softmax_gpu.cpp:92:9: note: here
         case softmax::normalize_yx:     kd.data_set_size *= input_size.spatial[1];
         ^~~~
/projects/cldnn/src/gpu/softmax_gpu.cpp:92:58: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case softmax::normalize_yx:     kd.data_set_size *= input_size.spatial[1];
/projects/cldnn/src/gpu/softmax_gpu.cpp:93:9: note: here
         case softmax::normalize_x:      kd.data_set_size *= input_size.spatial[0];
         ^~~~
cc1plus: all warnings being treated as errors