gcc-7.1: ambiguous else
Despite the efforts to avoid it with

// The GNU compiler emits a warning if nested "if" statements are followed by
// an "else" statement and braces are not used to explicitly disambiguate the
// "else" binding.  This leads to problems with code like:
//
//   if (gate)
//     ASSERT_*(condition) << "Some message";
//
// The "switch (0) case 0:" idiom is used to suppress this.
#ifdef __INTEL_COMPILER
# define GTEST_AMBIGUOUS_ELSE_BLOCKER_
#else
# define GTEST_AMBIGUOUS_ELSE_BLOCKER_ switch (0) case 0: default:  // NOLINT
#endif


on gcc 7.1, the following error appears

[ 83%] Building CXX object tests/CMakeFiles/tests.dir/test_cases/scale_gpu_test.cpp.o
/projects/cldnn/tests/test_cases/scale_gpu_test.cpp: In member function ‘virtual void NegativeScaleTest_TestAll_Test::TestBody()’:
/projects/cldnn/tests/test_cases/scale_gpu_test.cpp:1147:12: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
         if (i != j)
            ^
cc1plus: all warnings being treated as errors